name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  runTests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      #Runs 'npm ci' to install all node modules
      - name: install node modules
        run: npm ci
      
      #Runs test suites to check for testing errors  
      - name: run test suites
        run: npm test

      #Installs ESLint
      - name: install ESLint
        run: npm install eslint
      
      #Runs ESLint
      - name: check for linting errors
        run: ./node_modules/.bin/eslint
  
      #Deploy to Heroku by pushing to remote heroku git repo
      - name: deploy app to heroku
        run: git push https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ HEROKU_APP_NAME }}.git origin/master:master
  
        
