name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      #Runs 'npm ci' to install all node modules
      #Runs test suites to check for testing errors
      - run: npm ci
      - run: npm test
        
      # Installs & runs ESLint to check for linting errors
      - name: install the linter
        run: npm install eslint
      - run: ./node_modules/.bin/eslint
        
